### ISSUE TITLE
Missing some vpnt stats

### ISSUE THREAD

**Issue by itsbmr** [ptrsploit/CPViewer---CheckPoint-GW-performance-analysis-tool#1]
Hi,

thanks for creating this tool, it is just what I need. However I have one issue. 
I have a number of tunnel interfaces connecting to AWS accounts vpnt1 .. 6

I can see RX_bit_"vpnt1" to RX_bit_"vpnt6"
But I can only see TX_bit_"vpnt2" and TX_bit_"vpnt4"

Transmit bits for tunnel interfaces 1 3 5 6 are missing. 

Any ideas? 
Kind Regards

Bruce Richardson

**Comment by bc1petar** [comment]
Hi Bruce,

I'm glad you find it useful!

I am assuming that in the version which the GWs from which cpview.dat was
exported has some changes in the DB regarding the parameter names. I'd
suggest checking the parameters you need in the DB Plot and then compare
them to the engine which takes parameters from .dat within CPViewer. The
location of the engine which does all the data extraction is
/var/www/html/bash/CPview_influx81.sh and CPview_influx80.sh. You should be
able to find the sqlite lines which are relevant for your case there.

Cheers,
Petar

**Comment by itsbmr** [comment]
I'm closing this, I think it's just my misunderstanding of how Graphana works.
